### ISSUE TITLE
Create a models.py

### ISSUE THREAD

**Issue by tianpei2** [nyu-devops-fa19/customers#18]
**As a** developer 
**I need** to create a models.py file 
**So that** hold the model definitions of the resource

#### Assumptions
 - first name(String)
 - last name(String)
 - customer id (as key, generated by system so it's always unique from each other)
 - userid (should be unique, will do the check when create API is called.)
(String)
 - password(String)
 - at least one address(String)
 - addresses(List of strings)
 - serialize function
 - deserialize function

**Comment by dracarys21** [comment]
As of now, we're storing a single address for every customer with a 1-1 mapping b/w customer and address. In the future we need the capability to store multiple addresses for a customer. A new ticket has been created for this.
