### ISSUE TITLE
The Create API

### ISSUE THREAD

**Issue by myang39** [nyu-devops-fa19/customers#2]
**As a** customer
**I need** to be able to create my account 
**So that** I can have an account

#### Assumptions
 - first name
 - last name
 - customer id (as key, generated by system so it's always unique from each other)
 - userid (should be unique, will do the check when create API is called.)
 - password
 - at least one address
 - addresses

 - endpoint `POST /customers` 
#### Acceptance Criteria  
 - *Given* first name, last name, userid, password, and one address
 - *When* customer call the API with the Given fields all filled
 - *Then*  If a customer account is successfully created, return code as `201 (OK)`, and also return a json of all the fields and values of the account.
 - If the process is unsuccessful, return the responding error code.

**Comment by qtds35k** [comment]
Just a quick reminder: now that we have the **boolean** field `activate` in Customer, we might have to initiate it as **true** while creating an account?
