### ISSUE TITLE
Modify application to get the database credentials

### ISSUE THREAD

**Issue by qtds35k** [nyu-devops-fa19/customers#67]
**As a** developer  
**I need** get the database credentials
**So that** credentials will be available during runtime in an environment variable called: VCAP_SERVICE

#### Assumptions
 - DATABASE_URI by using PostgreSQL

#### Acceptance Criteria  
 - *Given* a created Service Credentials
 - *When* we load the VCAP_SERVICE
 - *Then* it will give us the `hostname`, `password`, and `port`

**Comment by tianpei2** [comment]
![image](https://user-images.githubusercontent.com/26192747/68533344-67cdb900-02f5-11ea-9aae-91bb9f196ea6.png)

![image](https://user-images.githubusercontent.com/26192747/68533341-54225280-02f5-11ea-90aa-499d0f2659e7.png)
